"""Self-contained HTML run report (opt-in, ``report.html_report``).

Renders a single portable ``.html`` file -- charts are matplotlib figures
embedded as base64 PNGs, so there are no external assets, no CDN, and no
JavaScript. Built from the read-tracking table plus a headline-summary dict.

matplotlib is an optional dependency: it is imported lazily, and if it is
missing the report still renders (table + summary + warnings) with a
``[WARN]`` instead of crashing (CLAUDE.md section 4).
"""

import base64
import io
from pathlib import Path
from typing import Dict, List, Optional, Union

import pandas as pd
from jinja2 import Template

from seednap.steps.report.read_tracking import DADA2_STEPS
from seednap.utils.logging import get_logger

# Steps are taken from the builder when available; this is the fallback.
_DEFAULT_STEPS = DADA2_STEPS

logger = get_logger(__name__)

_TEMPLATE = Template(
    """<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>SeeDNAP run report &mdash; {{ marker }}</title>
<style>
  :root { --bg:#0f172a; --card:#1e293b; --ink:#e2e8f0; --muted:#94a3b8;
          --accent:#38bdf8; --good:#34d399; --warn:#fbbf24; --bad:#f87171; --line:#334155; }
  * { box-sizing:border-box; }
  body { margin:0; font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;
         background:var(--bg); color:var(--ink); line-height:1.5; }
  .wrap { max-width:1100px; margin:0 auto; padding:32px 24px 64px; }
  header { border-bottom:1px solid var(--line); padding-bottom:20px; margin-bottom:28px; }
  h1 { margin:0 0 4px; font-size:26px; letter-spacing:.3px; }
  h1 .marker { color:var(--accent); }
  .sub { color:var(--muted); font-size:14px; }
  h2 { font-size:18px; margin:34px 0 14px; border-left:3px solid var(--accent); padding-left:10px; }
  .cards { display:grid; grid-template-columns:repeat(auto-fit,minmax(150px,1fr)); gap:14px; }
  .card { background:var(--card); border:1px solid var(--line); border-radius:12px; padding:16px 18px; }
  .card .v { font-size:24px; font-weight:700; }
  .card .l { color:var(--muted); font-size:12px; text-transform:uppercase; letter-spacing:.6px; margin-top:4px; }
  .chart { background:var(--card); border:1px solid var(--line); border-radius:12px; padding:14px; margin:14px 0; }
  .chart img { width:100%; height:auto; display:block; border-radius:6px; }
  table { width:100%; border-collapse:collapse; font-size:13px; }
  th,td { padding:7px 10px; text-align:right; border-bottom:1px solid var(--line); }
  th:first-child, td:first-child { text-align:left; }
  thead th { color:var(--muted); text-transform:uppercase; font-size:11px; letter-spacing:.5px; }
  tr.low td { color:var(--bad); }
  .na { color:var(--muted); }
  .warns { background:var(--card); border:1px solid var(--line); border-left:3px solid var(--warn); border-radius:8px; padding:6px 0; }
  .warns div { padding:6px 16px; font-family:ui-monospace,SFMono-Regular,Menlo,monospace; font-size:12.5px; color:var(--warn); border-bottom:1px solid var(--line); }
  .warns div:last-child { border-bottom:none; }
  .ok { color:var(--good); padding:10px 16px; }
  footer { color:var(--muted); font-size:12px; margin-top:40px; border-top:1px solid var(--line); padding-top:14px; }
  code { background:#0b1222; padding:1px 6px; border-radius:5px; color:var(--accent); }
</style></head>
<body><div class="wrap">
<header>
  <h1>SeeDNAP run report &mdash; <span class="marker">{{ marker }}</span></h1>
  <div class="sub">{{ subtitle }}</div>
</header>

<div class="cards">
  {% for c in cards %}<div class="card"><div class="v">{{ c.value }}</div><div class="l">{{ c.label }}</div></div>{% endfor %}
</div>

{% if charts %}<h2>Charts</h2>
  {% for ch in charts %}<div class="chart"><img alt="{{ ch.alt }}" src="data:image/png;base64,{{ ch.b64 }}"></div>{% endfor %}
{% endif %}

<h2>Notable events {% if warnings %}({{ warnings|length }}){% endif %}</h2>
{% if warnings %}<div class="warns">{% for w in warnings %}<div>{{ w }}</div>{% endfor %}</div>
{% else %}<div class="ok">No data-loss warnings &mdash; every sample passed the retention thresholds.</div>{% endif %}

<h2>Read tracking</h2>
<table><thead><tr><th>sample</th>{% for s in steps %}<th>{{ s }}</th>{% endfor %}<th>% retained</th></tr></thead>
<tbody>
{% for r in rows %}<tr class="{{ r.cls }}"><td>{{ r.sample }}</td>{% for c in r.cells %}<td class="{{ c.cls }}">{{ c.txt }}</td>{% endfor %}<td>{{ r.pct }}</td></tr>{% endfor %}
</tbody></table>

<footer>Generated by SeeDNAP &middot; self-contained report (no external assets){% if footer %} &middot; {{ footer }}{% endif %}</footer>
</div></body></html>
"""
)


class HTMLReportBuilder:
    """Render a self-contained HTML run report from the read-tracking table."""

    def __init__(
        self,
        marker: str,
        tracking_df: pd.DataFrame,
        warnings: Optional[List[str]] = None,
        summary: Optional[Dict[str, object]] = None,
        steps: Optional[List[str]] = None,
    ) -> None:
        self.marker = marker
        self.df = tracking_df if tracking_df is not None else pd.DataFrame()
        self.warnings = warnings or []
        self.summary = summary or {}
        # Step chain to render (DADA2 vs SWARM); infer from the table if absent.
        if steps:
            self.steps = steps
        else:
            self.steps = [c for c in _DEFAULT_STEPS if c in self.df.columns] or _DEFAULT_STEPS

    # ------------------------------------------------------------------
    # Charts (lazy matplotlib)
    # ------------------------------------------------------------------

    def _charts(self) -> List[Dict[str, str]]:
        if self.df.empty:
            return []
        try:
            import matplotlib
            matplotlib.use("Agg")
            import matplotlib.pyplot as plt
        except ImportError as exc:
            logger.warning(
                f"[WARN] html_report: expected=matplotlib for charts, "
                f"got=missing ({exc}), fallback=table-only report",
            )
            return []

        charts: List[Dict[str, str]] = []

        def _emit(fig, alt):
            buf = io.BytesIO()
            fig.savefig(buf, format="png", dpi=110, bbox_inches="tight",
                        facecolor="#1e293b")
            plt.close(fig)
            charts.append({"alt": alt, "b64": base64.b64encode(buf.getvalue()).decode()})

        ink, accent, grid = "#e2e8f0", "#38bdf8", "#334155"

        def _style(ax):
            ax.set_facecolor("#1e293b")
            for s in ax.spines.values():
                s.set_color(grid)
            ax.tick_params(colors=ink, labelsize=8)
            ax.yaxis.label.set_color(ink); ax.xaxis.label.set_color(ink)
            ax.title.set_color(ink)
            ax.grid(axis="y", color=grid, linewidth=0.5, alpha=0.6)

        # 1) Funnel: total reads surviving each step (sum across samples).
        totals = [pd.to_numeric(self.df[s], errors="coerce").sum(skipna=True)
                  for s in self.steps]
        if any(t > 0 for t in totals):
            fig, ax = plt.subplots(figsize=(8, 3.2), facecolor="#1e293b")
            ax.bar(self.steps, totals, color=accent)
            ax.set_title("Total reads surviving each step")
            ax.set_ylabel("read pairs")
            _style(ax)
            _emit(fig, "Reads surviving each step")

        # 2) Per-sample overall retention (%), sorted ascending.
        pr = pd.to_numeric(self.df["pct_retained"], errors="coerce").dropna()
        if not pr.empty:
            order = pr.sort_values()
            samples = self.df.loc[order.index, "sample"].astype(str).tolist()
            warn_pct = float(self.summary.get("warn_below_retention_pct", 30.0))
            colors = ["#f87171" if v < warn_pct else "#34d399" for v in order]
            fig, ax = plt.subplots(
                figsize=(8, max(2.4, 0.26 * len(order))), facecolor="#1e293b")
            ax.barh(range(len(order)), order.values, color=colors)
            ax.set_yticks(range(len(order))); ax.set_yticklabels(samples, fontsize=7)
            ax.axvline(warn_pct, color="#fbbf24", linewidth=1, linestyle="--")
            ax.set_title("Per-sample retention (raw → non-chimeric, %)")
            ax.set_xlabel("% retained")
            _style(ax); ax.grid(axis="x", color=grid, linewidth=0.5, alpha=0.6)
            _emit(fig, "Per-sample retention")

        return charts

    # ------------------------------------------------------------------
    # Render
    # ------------------------------------------------------------------

    def _cards(self) -> List[Dict[str, str]]:
        df = self.df
        n = len(df)
        def fmt(v):
            return "—" if v is None or pd.isna(v) else f"{int(v):,}"
        final_step = self.steps[-1] if self.steps else "raw"
        raw_total = pd.to_numeric(df["raw"], errors="coerce").sum() if n and "raw" in df else None
        final_total = (
            pd.to_numeric(df[final_step], errors="coerce").sum()
            if n and final_step in df else None
        )
        pr = pd.to_numeric(df["pct_retained"], errors="coerce") if n else pd.Series(dtype=float)
        mean_ret = pr.mean() if not pr.empty else None
        cards = [
            {"label": "samples", "value": f"{n:,}"},
            {"label": "raw reads", "value": fmt(raw_total)},
            {"label": f"{final_step} reads", "value": fmt(final_total)},
            {"label": "mean retention", "value": "—" if mean_ret is None or pd.isna(mean_ret) else f"{mean_ret:.1f}%"},
        ]
        for key, label in (("n_features", "OTUs/ASVs"), ("method", "taxonomy"),
                           ("cluster", "cluster")):
            if key in self.summary and self.summary[key] is not None:
                v = self.summary[key]
                cards.append({"label": label, "value": f"{v:,}" if isinstance(v, int) else str(v)})
        return cards

    def _rows(self) -> List[Dict[str, object]]:
        rows = []
        warn_pct = float(self.summary.get("warn_below_retention_pct", 30.0))
        for _, r in self.df.iterrows():
            cells = []
            for s in self.steps:
                v = r[s]
                if pd.isna(v):
                    cells.append({"txt": "NA", "cls": "na"})
                else:
                    cells.append({"txt": f"{int(v):,}", "cls": ""})
            pr = r["pct_retained"]
            low = pd.notna(pr) and pr < warn_pct
            rows.append({
                "sample": r["sample"],
                "cells": cells,
                "pct": "NA" if pd.isna(pr) else f"{pr:.1f}%",
                "cls": "low" if low else "",
            })
        return rows

    def render(self) -> str:
        subtitle = self.summary.get("subtitle") or f"{len(self.df)} samples"
        return _TEMPLATE.render(
            marker=self.marker,
            subtitle=subtitle,
            cards=self._cards(),
            charts=self._charts(),
            warnings=self.warnings,
            steps=self.steps,
            rows=self._rows(),
            footer=self.summary.get("footer"),
        )

    def write(self, output_path: Union[str, Path]) -> Path:
        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(self.render(), encoding="utf-8")
        logger.info(f"Wrote HTML run report: {path}")
        return path
